#!/bin/bash

export NUM="${1:-0}"
export NAMESPACE="${2:-basseng}"

cat > nais.yaml <<EOF
kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: db-tester-${NUM}
  namespace: ${NAMESPACE}
  labels:
    team: ${NAMESPACE}
spec:
  image: ghcr.io/navikt/nada-db-test:v11
  port: 8080
  replicas:
    min: 2
    max: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_13
        tier: db-custom-1-4096
        name: not-same-as-app-${NUM}
        cascadingDelete: true
        databases:
          - name: nada-db-test
            envVarPrefix: DB
EOF

kubectl apply -f nais.yaml
