#!/bin/bash

export ACTION="${1}"
export NUM=${2:-"0"}

script_path=$(dirname "$(realpath -s "$0")")

if [[ -z "${ACTION}" ]]; then
  echo "Usage: $0 <action> [num]"
  exit 1
fi

pushd "${script_path}/.." || exit 1
make all
popd || exit 2

while IFS="" read -r p
do
  if [[ -z "${p}" ]]; then
    continue
  fi
  eval export "${p}"
done < "${script_path}/env"

exe_path="${script_path}/../bin/${ACTION}"

echo "Executing ${exe_path} for application ${APP_NAME}"

${exe_path} | humanlog
