name: Build and deploy CloudSQL-migrator

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - '*.md'

env:
  GOOGLE_REGISTRY: "europe-north1-docker.pkg.dev"

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4 # ratchet:actions/checkout@v3
      - name: Install cosign
        uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.2.3'
      - name: Verify runner image
        run: cosign verify --certificate-identity keyless@distroless.iam.gserviceaccount.com --certificate-oidc-issuer https://accounts.google.com gcr.io/distroless/static-debian11
      - uses: nais/platform-build-push-sign@main # ratchet:exclude
        id: build-push-sign
        with:
          name: cloudsql-migrator
          google_service_account: gh-cloudsql-migrator
          push: ${{ github.actor != 'dependabot[bot]' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          multi-platform: true
          cache_from: type=gha
          cache_to: type=gha,mode=max
      - name: Create release
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ steps.build-push-sign.outputs.version }}"
          name: "Release ${{ steps.build-push-sign.outputs.version }}"
          draft: false
          prerelease: false
          generate_release_notes: true
    outputs:
      version: "${{ steps.build-push-sign.outputs.version }}"
